-- filme schema
drop table filme;
create table filme (
  id INTEGER PRIMARY KEY,
  sender VARCHAR,
  thema VARCHAR,
  titel VARCHAR,
  datum VARCHAR,
  zeit VARCHAR,
  dauer VARCHAR,
  mb VARCHAR,
  beschreibung VARCHAR,
  url VARCHAR,
  website VARCHAR,
  captions VARCHAR,
  urlRtmp VARCHAR,
  urlLD VARCHAR,
  urlRtmpLD VARCHAR,
  urlHD VARCHAR,
  urlRtmpHD VARCHAR,
  datumL VARCHAR,
  urlHistory VARCHAR,
  geo VARCHAR,
  neu VARCHAR,
  );
